// packages/website/src/components/solid/LiveDemoControlled.tsx
/** @jsxImportSource solid-js */
import { createResource, createSignal, Show } from 'solid-js';
import type { TegakiBundle } from 'tegaki/core';
import { TegakiRenderer } from 'tegaki/solid';

async function loadBundle(): Promise<TegakiBundle> {
  const mod = await import('tegaki/fonts/caveat');
  return (mod as any).default;
}

export function LiveDemoControlled(props: { fontSize?: number }) {
  const [bundle] = createResource(loadBundle);
  const [time, setTime] = createSignal(0);

  return (
    <div class="not-content live-demo">
      <div class="live-demo-card">
        <Show when={bundle()} fallback={<div class="live-demo-loading">Loading...</div>}>
          {(b) => (
            <>
              <input
                type="range"
                min={0}
                max={10}
                step={0.01}
                value={time()}
                onInput={(e) => setTime(Number(e.currentTarget.value))}
                class="live-demo-slider"
              />
              <TegakiRenderer font={b()} text="Scrub me!" time={time()} style={{ 'font-size': `${props.fontSize ?? 48}px` }} />
            </>
          )}
        </Show>
      </div>
      <div class="live-demo-caption">Drag the slider to scrub through the animation</div>
    </div>
  );
}

// packages/website/src/components/svelte/LiveDemoControlled.svelte
<script lang="ts">
import { TegakiRenderer } from 'tegaki/svelte';
import type { TegakiBundle } from 'tegaki/core';

let { fontSize = 48 }: { fontSize?: number } = $props();

let bundle = $state<TegakiBundle | null>(null);
let time = $state(0);

$effect(() => {
  import('tegaki/fonts/caveat').then((mod) => {
    bundle = (mod as any).default;
  });
});
</script>

<div class="not-content live-demo">
  <div class="live-demo-card">
    {#if bundle}
      <input type="range" min={0} max={10} step={0.01} bind:value={time} class="live-demo-slider" />
      <TegakiRenderer font={bundle} text="Scrub me!" {time} style="font-size: {fontSize}px" />
    {:else}
      <div class="live-demo-loading">Loading...</div>
    {/if}
  </div>
  <div class="live-demo-caption">Drag the slider to scrub through the animation</div>
</div>
